version: 2.1

orbs:
  architect: giantswarm/architect@5.11.4

workflows:
  build:
    jobs:
    - architect/go-build:
        name: go-build
        context: architect
        binary: capa-karpenter-taint-remover
        filters:
          tags:
            only: /^v.*/

    - architect/push-to-registries:
        context: architect
        name: push-to-registries
        requires:
        - go-build
        filters:
          tags:
            only: /^v.*/
          branches:
            only: /.*/
    - architect/push-to-app-catalog:
        context: architect
        name: push-capa-karpenter-taint-remover-to-app-catalog
        executor: app-build-suite
        app_catalog: control-plane-catalog
        app_catalog_test: control-plane-test-catalog
        chart: capa-karpenter-taint-remover
        requires:
        - push-to-registries
        filters:
          tags:
            only: /^v.*/
          branches:
            only: /.*/ 
