apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
  {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
  {{- include "labels.selector" . | nindent 6 }}
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
    {{- include "labels.selector" . | nindent 8 }}
    spec:
      containers:
        - name: "karpenter-taint-remover"
          {{- if gt (len .Values.unwantedTaints) 0 }}
          args:
            - --unwanted-taints={{ .Values.unwantedTaints | join "," | quote }}
          {{- end }}
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            seccompProfile:
              type: RuntimeDefault
            capabilities:
              drop:
                - ALL
      nodeSelector:
        karpenter.sh/registered: "true"
      priorityClassName: system-node-critical
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: {{ include "resource.default.name" . }}
      terminationGracePeriodSeconds: 0
      tolerations:
        - operator: Exists
