apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
  {{- include "labels.common" . | nindent 4 }}
  name: {{ include "resource.default.name" . }}
  namespace: {{ include "resource.default.namespace" . }}
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
  {{- include "labels.selector" . | nindent 6 }}
  template:
    metadata:
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ""
      labels:
    {{- include "labels.selector" . | nindent 8 }}
    spec:
      containers:
        - name: "karpenter-taint-remover"
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
      nodeSelector:
        managed-by: karpenter
      priorityClassName: system-node-critical
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: {{ include "resource.default.name" . }}
      terminationGracePeriodSeconds: 0
      tolerations:
        - key: node.cluster.x-k8s.io/uninitialized
          operator: Exists
        - key: node.kubernetes.io/not-ready
          operator: Exists
